import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./home/sections/NavBar";
import Footer from "./home/sections/Footer";

export const metadata: Metadata = {
  title: "UI/UX Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
